baseURL: https://goppydae.github.io/sharur/
languageCode: en-us
title: Sharur

taxonomies:
  category: categories
  tag: tags

module:
  imports:
    - path: github.com/McShelby/hugo-theme-relearn

menu:
  taxonomylinks:
    - name: Categories
      url: /categories/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2

params:
  themeVariant:
    - auto:
        - zen-light
        - github-dark
  disableRootBreadcrumb: false
  disableTermBreadcrumbs: false
  disableNextPrev: false
  titleSeparator: "-"
  search:
    disable: false
  editURL: https://github.com/goppydae/sharur/edit/main/docs/content/

  sidebarheadermenus:
    - type: divider
    - identifier: headercontrols
      type: custom
      elements:
        - type: homelink
        - type: githublink
          url: "https://github.com/goppydae/sharur"
          label: GitHub
        - type: pkgsite
          repo: "github.com/goppydae/sharur"
    - type: divider

  sidebarfootermenus:
    - type: divider
    - identifier: taxonomylinks
      type: menu
    - type: divider
    - identifier: footercontrols
      elements:
        - type: historyclearer
        - type: variantswitcher
        - type: languageswitcher
      type: custom

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false

outputs:
  home:
    - html
    - rss
    - markdown
    - source
    - print
  page:
    - html
    - rss
    - markdown
    - source
    - print
  rss:
    - html
    - rss
    - markdown
    - source
    - print
  section:
    - html
    - rss
    - markdown
    - source
    - print
  taxonomy:
    - html
    - rss
    - print
  term:
    - html
    - rss
    - print
