baseURL: https://goppydae.github.io/gollm/
languageCode: en-us
title: Gollm

module:
  imports:
    - path: github.com/McShelby/hugo-theme-relearn

params:
  themeVariant:
    - auto:
        - zen-light
        - zen-dark
  disableRootBreadcrumb: false
  disableTermBreadcrumbs: false
  disableNextPrev: false
  titleSeparator: "-"
  search:
    disable: false
  editURL: https://github.com/goppydae/gollm/edit/main/docs/content/

  sidebarheadermenus:
    - type: divider
    - identifier: headercontrols
      type: custom
      elements:
        - type: homelink
        - type: githublink
          url: "https://github.com/goppydae/gollm"
          label: GitHub
        - type: pkgsite
          repo: "github.com/goppydae/gollm"
    - type: divider

  sidebarfootermenus:
    - type: divider
    - identifier: footercontrols
      elements:
        - type: historyclearer
        - type: variantswitcher
        - type: languageswitcher
      type: custom

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: monokai
