// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: extensions/proto/extension.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_extensions_proto_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{0}
}

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_extensions_proto_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{1}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ToolDefinition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJsonSchema string                 `protobuf:"bytes,3,opt,name=parameters_json_schema,json=parametersJsonSchema,proto3" json:"parameters_json_schema,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_extensions_proto_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{2}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParametersJsonSchema() string {
	if x != nil {
		return x.ParametersJsonSchema
	}
	return ""
}

type ToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefinition      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsResponse) Reset() {
	*x = ToolsResponse{}
	mi := &file_extensions_proto_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsResponse) ProtoMessage() {}

func (x *ToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsResponse.ProtoReflect.Descriptor instead.
func (*ToolsResponse) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{3}
}

func (x *ToolsResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

// Represents the state passed to BeforePrompt
type AgentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ThinkingLevel string                 `protobuf:"bytes,4,opt,name=thinking_level,json=thinkingLevel,proto3" json:"thinking_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	mi := &file_extensions_proto_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{4}
}

func (x *AgentState) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AgentState) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentState) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentState) GetThinkingLevel() string {
	if x != nil {
		return x.ThinkingLevel
	}
	return ""
}

type BeforePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *AgentState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeforePromptRequest) Reset() {
	*x = BeforePromptRequest{}
	mi := &file_extensions_proto_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeforePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeforePromptRequest) ProtoMessage() {}

func (x *BeforePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeforePromptRequest.ProtoReflect.Descriptor instead.
func (*BeforePromptRequest) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{5}
}

func (x *BeforePromptRequest) GetState() *AgentState {
	if x != nil {
		return x.State
	}
	return nil
}

type BeforePromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *AgentState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeforePromptResponse) Reset() {
	*x = BeforePromptResponse{}
	mi := &file_extensions_proto_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeforePromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeforePromptResponse) ProtoMessage() {}

func (x *BeforePromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeforePromptResponse.ProtoReflect.Descriptor instead.
func (*BeforePromptResponse) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{6}
}

func (x *BeforePromptResponse) GetState() *AgentState {
	if x != nil {
		return x.State
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_extensions_proto_extension_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_extensions_proto_extension_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{8}
}

func (x *ToolResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AfterToolCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Call          *ToolCall              `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	Result        *ToolResult            `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterToolCallRequest) Reset() {
	*x = AfterToolCallRequest{}
	mi := &file_extensions_proto_extension_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterToolCallRequest) ProtoMessage() {}

func (x *AfterToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterToolCallRequest.ProtoReflect.Descriptor instead.
func (*AfterToolCallRequest) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{9}
}

func (x *AfterToolCallRequest) GetCall() *ToolCall {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *AfterToolCallRequest) GetResult() *ToolResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type AfterToolCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ToolResult            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterToolCallResponse) Reset() {
	*x = AfterToolCallResponse{}
	mi := &file_extensions_proto_extension_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterToolCallResponse) ProtoMessage() {}

func (x *AfterToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterToolCallResponse.ProtoReflect.Descriptor instead.
func (*AfterToolCallResponse) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{10}
}

func (x *AfterToolCallResponse) GetResult() *ToolResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ModifySystemPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPrompt string                 `protobuf:"bytes,1,opt,name=current_prompt,json=currentPrompt,proto3" json:"current_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifySystemPromptRequest) Reset() {
	*x = ModifySystemPromptRequest{}
	mi := &file_extensions_proto_extension_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifySystemPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySystemPromptRequest) ProtoMessage() {}

func (x *ModifySystemPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySystemPromptRequest.ProtoReflect.Descriptor instead.
func (*ModifySystemPromptRequest) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{11}
}

func (x *ModifySystemPromptRequest) GetCurrentPrompt() string {
	if x != nil {
		return x.CurrentPrompt
	}
	return ""
}

type ModifySystemPromptResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModifiedPrompt string                 `protobuf:"bytes,1,opt,name=modified_prompt,json=modifiedPrompt,proto3" json:"modified_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModifySystemPromptResponse) Reset() {
	*x = ModifySystemPromptResponse{}
	mi := &file_extensions_proto_extension_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifySystemPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySystemPromptResponse) ProtoMessage() {}

func (x *ModifySystemPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_extension_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySystemPromptResponse.ProtoReflect.Descriptor instead.
func (*ModifySystemPromptResponse) Descriptor() ([]byte, []int) {
	return file_extensions_proto_extension_proto_rawDescGZIP(), []int{12}
}

func (x *ModifySystemPromptResponse) GetModifiedPrompt() string {
	if x != nil {
		return x.ModifiedPrompt
	}
	return ""
}

var File_extensions_proto_extension_proto protoreflect.FileDescriptor

const file_extensions_proto_extension_proto_rawDesc = "" +
	"\n" +
	" extensions/proto/extension.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"|\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x124\n" +
	"\x16parameters_json_schema\x18\x03 \x01(\tR\x14parametersJsonSchema\"<\n" +
	"\rToolsResponse\x12+\n" +
	"\x05tools\x18\x01 \x03(\v2\x15.proto.ToolDefinitionR\x05tools\"$\n" +
	"\n" +
	"AgentState\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\">\n" +
	"\x13BeforePromptRequest\x12'\n" +
	"\x05state\x18\x01 \x01(\v2\x11.proto.AgentStateR\x05state\"?\n" +
	"\x14BeforePromptResponse\x12'\n" +
	"\x05state\x18\x01 \x01(\v2\x11.proto.AgentStateR\x05state\"E\n" +
	"\bToolCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\":\n" +
	"\n" +
	"ToolResult\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"f\n" +
	"\x14AfterToolCallRequest\x12#\n" +
	"\x04call\x18\x01 \x01(\v2\x0f.proto.ToolCallR\x04call\x12)\n" +
	"\x06result\x18\x02 \x01(\v2\x11.proto.ToolResultR\x06result\"B\n" +
	"\x15AfterToolCallResponse\x12)\n" +
	"\x06result\x18\x01 \x01(\v2\x11.proto.ToolResultR\x06result\"B\n" +
	"\x19ModifySystemPromptRequest\x12%\n" +
	"\x0ecurrent_prompt\x18\x01 \x01(\tR\rcurrentPrompt\"E\n" +
	"\x1aModifySystemPromptResponse\x12'\n" +
	"\x0fmodified_prompt\x18\x01 \x01(\tR\x0emodifiedPrompt2\xd3\x02\n" +
	"\tExtension\x12)\n" +
	"\x04Name\x12\f.proto.Empty\x1a\x13.proto.NameResponse\x12+\n" +
	"\x05Tools\x12\f.proto.Empty\x1a\x14.proto.ToolsResponse\x12G\n" +
	"\fBeforePrompt\x12\x1a.proto.BeforePromptRequest\x1a\x1b.proto.BeforePromptResponse\x12J\n" +
	"\rAfterToolCall\x12\x1b.proto.AfterToolCallRequest\x1a\x1c.proto.AfterToolCallResponse\x12Y\n" +
	"\x12ModifySystemPrompt\x12 .proto.ModifySystemPromptRequest\x1a!.proto.ModifySystemPromptResponseB\x18Z\x16gollm/extensions/protob\x06proto3"

var (
	file_extensions_proto_extension_proto_rawDescOnce sync.Once
	file_extensions_proto_extension_proto_rawDescData []byte
)

func file_extensions_proto_extension_proto_rawDescGZIP() []byte {
	file_extensions_proto_extension_proto_rawDescOnce.Do(func() {
		file_extensions_proto_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_proto_extension_proto_rawDesc), len(file_extensions_proto_extension_proto_rawDesc)))
	})
	return file_extensions_proto_extension_proto_rawDescData
}

var file_extensions_proto_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_extensions_proto_extension_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: proto.Empty
	(*NameResponse)(nil),               // 1: proto.NameResponse
	(*ToolDefinition)(nil),             // 2: proto.ToolDefinition
	(*ToolsResponse)(nil),              // 3: proto.ToolsResponse
	(*AgentState)(nil),                 // 4: proto.AgentState
	(*BeforePromptRequest)(nil),        // 5: proto.BeforePromptRequest
	(*BeforePromptResponse)(nil),       // 6: proto.BeforePromptResponse
	(*ToolCall)(nil),                   // 7: proto.ToolCall
	(*ToolResult)(nil),                 // 8: proto.ToolResult
	(*AfterToolCallRequest)(nil),       // 9: proto.AfterToolCallRequest
	(*AfterToolCallResponse)(nil),      // 10: proto.AfterToolCallResponse
	(*ModifySystemPromptRequest)(nil),  // 11: proto.ModifySystemPromptRequest
	(*ModifySystemPromptResponse)(nil), // 12: proto.ModifySystemPromptResponse
}
var file_extensions_proto_extension_proto_depIdxs = []int32{
	2,  // 0: proto.ToolsResponse.tools:type_name -> proto.ToolDefinition
	4,  // 1: proto.BeforePromptRequest.state:type_name -> proto.AgentState
	4,  // 2: proto.BeforePromptResponse.state:type_name -> proto.AgentState
	7,  // 3: proto.AfterToolCallRequest.call:type_name -> proto.ToolCall
	8,  // 4: proto.AfterToolCallRequest.result:type_name -> proto.ToolResult
	8,  // 5: proto.AfterToolCallResponse.result:type_name -> proto.ToolResult
	0,  // 6: proto.Extension.Name:input_type -> proto.Empty
	0,  // 7: proto.Extension.Tools:input_type -> proto.Empty
	5,  // 8: proto.Extension.BeforePrompt:input_type -> proto.BeforePromptRequest
	9,  // 9: proto.Extension.AfterToolCall:input_type -> proto.AfterToolCallRequest
	11, // 10: proto.Extension.ModifySystemPrompt:input_type -> proto.ModifySystemPromptRequest
	1,  // 11: proto.Extension.Name:output_type -> proto.NameResponse
	3,  // 12: proto.Extension.Tools:output_type -> proto.ToolsResponse
	6,  // 13: proto.Extension.BeforePrompt:output_type -> proto.BeforePromptResponse
	10, // 14: proto.Extension.AfterToolCall:output_type -> proto.AfterToolCallResponse
	12, // 15: proto.Extension.ModifySystemPrompt:output_type -> proto.ModifySystemPromptResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_extensions_proto_extension_proto_init() }
func file_extensions_proto_extension_proto_init() {
	if File_extensions_proto_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_proto_extension_proto_rawDesc), len(file_extensions_proto_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extensions_proto_extension_proto_goTypes,
		DependencyIndexes: file_extensions_proto_extension_proto_depIdxs,
		MessageInfos:      file_extensions_proto_extension_proto_msgTypes,
	}.Build()
	File_extensions_proto_extension_proto = out.File
	file_extensions_proto_extension_proto_goTypes = nil
	file_extensions_proto_extension_proto_depIdxs = nil
}
