// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: extensions/proto/extension.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Extension_Name_FullMethodName               = "/proto.Extension/Name"
	Extension_Tools_FullMethodName              = "/proto.Extension/Tools"
	Extension_ExecuteTool_FullMethodName        = "/proto.Extension/ExecuteTool"
	Extension_BeforePrompt_FullMethodName       = "/proto.Extension/BeforePrompt"
	Extension_AfterToolCall_FullMethodName      = "/proto.Extension/AfterToolCall"
	Extension_ModifySystemPrompt_FullMethodName = "/proto.Extension/ModifySystemPrompt"
)

// ExtensionClient is the client API for Extension service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionClient interface {
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error)
	Tools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToolsResponse, error)
	// ExecuteTool asks the extension process to execute one of its tools.
	// Request reuses ToolCall (name + arguments_json); response reuses ToolResult (output + error).
	ExecuteTool(ctx context.Context, in *ToolCall, opts ...grpc.CallOption) (*ToolResult, error)
	BeforePrompt(ctx context.Context, in *BeforePromptRequest, opts ...grpc.CallOption) (*BeforePromptResponse, error)
	AfterToolCall(ctx context.Context, in *AfterToolCallRequest, opts ...grpc.CallOption) (*AfterToolCallResponse, error)
	ModifySystemPrompt(ctx context.Context, in *ModifySystemPromptRequest, opts ...grpc.CallOption) (*ModifySystemPromptResponse, error)
}

type extensionClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionClient(cc grpc.ClientConnInterface) ExtensionClient {
	return &extensionClient{cc}
}

func (c *extensionClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, Extension_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) Tools(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolsResponse)
	err := c.cc.Invoke(ctx, Extension_Tools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) ExecuteTool(ctx context.Context, in *ToolCall, opts ...grpc.CallOption) (*ToolResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResult)
	err := c.cc.Invoke(ctx, Extension_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) BeforePrompt(ctx context.Context, in *BeforePromptRequest, opts ...grpc.CallOption) (*BeforePromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeforePromptResponse)
	err := c.cc.Invoke(ctx, Extension_BeforePrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) AfterToolCall(ctx context.Context, in *AfterToolCallRequest, opts ...grpc.CallOption) (*AfterToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AfterToolCallResponse)
	err := c.cc.Invoke(ctx, Extension_AfterToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) ModifySystemPrompt(ctx context.Context, in *ModifySystemPromptRequest, opts ...grpc.CallOption) (*ModifySystemPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifySystemPromptResponse)
	err := c.cc.Invoke(ctx, Extension_ModifySystemPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtensionServer is the server API for Extension service.
// All implementations must embed UnimplementedExtensionServer
// for forward compatibility.
type ExtensionServer interface {
	Name(context.Context, *Empty) (*NameResponse, error)
	Tools(context.Context, *Empty) (*ToolsResponse, error)
	ExecuteTool(context.Context, *ToolCall) (*ToolResult, error)
	BeforePrompt(context.Context, *BeforePromptRequest) (*BeforePromptResponse, error)
	AfterToolCall(context.Context, *AfterToolCallRequest) (*AfterToolCallResponse, error)
	ModifySystemPrompt(context.Context, *ModifySystemPromptRequest) (*ModifySystemPromptResponse, error)
	mustEmbedUnimplementedExtensionServer()
}

// UnimplementedExtensionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionServer struct{}

func (UnimplementedExtensionServer) Name(context.Context, *Empty) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedExtensionServer) Tools(context.Context, *Empty) (*ToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tools not implemented")
}
func (UnimplementedExtensionServer) ExecuteTool(context.Context, *ToolCall) (*ToolResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedExtensionServer) BeforePrompt(context.Context, *BeforePromptRequest) (*BeforePromptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeforePrompt not implemented")
}
func (UnimplementedExtensionServer) AfterToolCall(context.Context, *AfterToolCallRequest) (*AfterToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AfterToolCall not implemented")
}
func (UnimplementedExtensionServer) ModifySystemPrompt(context.Context, *ModifySystemPromptRequest) (*ModifySystemPromptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifySystemPrompt not implemented")
}
func (UnimplementedExtensionServer) mustEmbedUnimplementedExtensionServer() {}
func (UnimplementedExtensionServer) testEmbeddedByValue()                   {}

// UnsafeExtensionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionServer will
// result in compilation errors.
type UnsafeExtensionServer interface {
	mustEmbedUnimplementedExtensionServer()
}

func RegisterExtensionServer(s grpc.ServiceRegistrar, srv ExtensionServer) {
	// If the following call panics, it indicates UnimplementedExtensionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Extension_ServiceDesc, srv)
}

func _Extension_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_Tools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).Tools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_Tools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).Tools(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).ExecuteTool(ctx, req.(*ToolCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_BeforePrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeforePromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).BeforePrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_BeforePrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).BeforePrompt(ctx, req.(*BeforePromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_AfterToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AfterToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).AfterToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_AfterToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).AfterToolCall(ctx, req.(*AfterToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_ModifySystemPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifySystemPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).ModifySystemPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extension_ModifySystemPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).ModifySystemPrompt(ctx, req.(*ModifySystemPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Extension_ServiceDesc is the grpc.ServiceDesc for Extension service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Extension_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Extension",
	HandlerType: (*ExtensionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _Extension_Name_Handler,
		},
		{
			MethodName: "Tools",
			Handler:    _Extension_Tools_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _Extension_ExecuteTool_Handler,
		},
		{
			MethodName: "BeforePrompt",
			Handler:    _Extension_BeforePrompt_Handler,
		},
		{
			MethodName: "AfterToolCall",
			Handler:    _Extension_AfterToolCall_Handler,
		},
		{
			MethodName: "ModifySystemPrompt",
			Handler:    _Extension_ModifySystemPrompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extensions/proto/extension.proto",
}
